### ISSUE TITLE
Windows Setup Failure, including wheels

### ISSUE THREAD

**Issue by DylanTurnley** [UIUC-PPL/charm4py#179]
Hello, 

I am terribly sorry but I am really struggling to fix the following issue

I have tried installing: MPI and MPI4py, as well as all the 

When trying to run the following via pip:

This is the reposnce:

C:\>pip install charm4py
Collecting charm4py
  Using cached charm4py-1.0.tar.gz (3.4 MB)
Requirement already satisfied: numpy>=1.10.0 in c:\users\dylan\appdata\local\programs\python\python37-32\lib\site-packages (from charm4py) (1.18.5)
Requirement already satisfied: greenlet in c:\users\dylan\appdata\local\programs\python\python37-32\lib\site-packages (from charm4py) (0.4.16)
Building wheels for collected packages: charm4py
  Building wheel for charm4py (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\dylan\appdata\local\programs\python\python37-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Dylan\\AppData\\Local\\Temp\\pip-install-vrwss169\\charm4py\\setup.py'"'"'; __file__='"'"'C:\\Users\\Dylan\\AppData\\Local\\Temp\\pip-install-vrwss169\\charm4py\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\Dylan\AppData\Local\Temp\pip-wheel-5sx356ud'
       cwd: C:\Users\Dylan\AppData\Local\Temp\pip-install-vrwss169\charm4py\
  Complete output (10 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win32-3.7
  creating build\lib.win32-3.7\charm4py
  creating build\lib.win32-3.7\charm4py\.libs
  creating C:\Users\Dylan\AppData\Local\Temp\pip-install-vrwss169\charm4py\charm4py\.libs
  creating build\lib.win32-3.7\charmrun
  error: Building charm++ from setup.py not currently supported on Windows. Please download a Charm4py binary wheel (64-bit Python required)
  ----------------------------------------
  ERROR: Failed building wheel for charm4py
  Running setup.py clean for charm4py
Failed to build charm4py
DEPRECATION: Could not build wheels for charm4py which do not use PEP 517. pip will fall back to legacy 'setup.py install' for these. pip 21.0 will remove support for this functionality. A possible replacement is to fix the wheel build issue reported above. You can find discussion regarding this at https://github.com/pypa/pip/issues/8368.
Installing collected packages: charm4py
    Running setup.py install for charm4py ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\dylan\appdata\local\programs\python\python37-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Dylan\\AppData\\Local\\Temp\\pip-install-vrwss169\\charm4py\\setup.py'"'"'; __file__='"'"'C:\\Users\\Dylan\\AppData\\Local\\Temp\\pip-install-vrwss169\\charm4py\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Dylan\AppData\Local\Temp\pip-record-ild1vqpv\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\dylan\appdata\local\programs\python\python37-32\Include\charm4py'
         cwd: C:\Users\Dylan\AppData\Local\Temp\pip-install-vrwss169\charm4py\
    Complete output (9 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win32-3.7
    creating build\lib.win32-3.7\charm4py
    creating build\lib.win32-3.7\charm4py\.libs
    creating build\lib.win32-3.7\charmrun
    error: Building charm++ from setup.py not currently supported on Windows. Please download a Charm4py binary wheel (64-bit Python required)
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\dylan\appdata\local\programs\python\python37-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Dylan\\AppData\\Local\\Temp\\pip-install-vrwss169\\charm4py\\setup.py'"'"'; __file__='"'"'C:\\Users\\Dylan\\AppData\\Local\\Temp\\pip-install-vrwss169\\charm4py\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Dylan\AppData\Local\Temp\pip-record-ild1vqpv\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\dylan\appdata\local\programs\python\python37-32\Include\charm4py' Check the logs for full command output.

When I run via no Binary option

I get:

C:\>pip3 install [--mpi] charm4py --no-binary charm4py
ERROR: Exception:
Traceback (most recent call last):
  File "c:\users\dylan\appdata\local\programs\python\python37-32\lib\site-packages\pip\_vendor\packaging\requirements.py", line 98, in __init__
    req = REQUIREMENT.parseString(requirement_string)
  File "c:\users\dylan\appdata\local\programs\python\python37-32\lib\site-packages\pip\_vendor\pyparsing.py", line 1955, in parseString
    raise exc
  File "c:\users\dylan\appdata\local\programs\python\python37-32\lib\site-packages\pip\_vendor\pyparsing.py", line 3814, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pip._vendor.pyparsing.ParseException: Expected stringEnd, found '['  (at char 11), (line:1, col:12)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\dylan\appdata\local\programs\python\python37-32\lib\site-packages\pip\_internal\cli\base_command.py", line 216, in _main
    status = self.run(options, args)
  File "c:\users\dylan\appdata\local\programs\python\python37-32\lib\site-packages\pip\_internal\cli\req_command.py", line 182, in wrapper
    return func(self, options, args)
  File "c:\users\dylan\appdata\local\programs\python\python37-32\lib\site-packages\pip\_internal\commands\install.py", line 295, in run
    reqs = self.get_requirements(args, options, finder, session)
  File "c:\users\dylan\appdata\local\programs\python\python37-32\lib\site-packages\pip\_internal\cli\req_command.py", line 319, in get_requirements
    user_supplied=True,
  File "c:\users\dylan\appdata\local\programs\python\python37-32\lib\site-packages\pip\_internal\req\constructors.py", line 409, in install_req_from_line
    parts = parse_req_from_line(name, line_source)
  File "c:\users\dylan\appdata\local\programs\python\python37-32\lib\site-packages\pip\_internal\req\constructors.py", line 349, in parse_req_from_line
    extras = convert_extras(extras_as_string)
  File "c:\users\dylan\appdata\local\programs\python\python37-32\lib\site-packages\pip\_internal\req\constructors.py", line 75, in convert_extras
    return Requirement("placeholder" + extras.lower()).extras
  File "c:\users\dylan\appdata\local\programs\python\python37-32\lib\site-packages\pip\_vendor\packaging\requirements.py", line 102, in __init__
    requirement_string[e.loc : e.loc + 8], e.msg
pip._vendor.packaging.requirements.InvalidRequirement: Parse error at "'[--mpi]'": Expected stringEnd

I  have also tried all the windows wheels and each says that they are not compatible.

Please help

**Comment by matthiasdiener** [comment]
Please try to download a precompiled wheel for Windows from here: https://pypi.org/project/charm4py/#files
